#!/usr/bin/env bash
chapter=$1
section=$2
exercise=$3
shift
shift
shift
java_args=$@
java_package=algsex/chapter$chapter/section$section/Exercise$exercise

run() {
  command="java -cp $JAVA_DEPS_DIR/*:$JAVA_OUTPUT_DIR $java_package $java_args"
  prompt "running command \u001b[34m$command\u001b[0m"
  $command
}

compile && run