#!/usr/bin/env bash
RED="\u001b[31m"
GREEN="\u001b[32m"
BLUE="\u001b[34m"
NO_COLOR="\u001b[0m"
CHECK_ICON="\xE2\x9C\x85"
ERROR_ICON="\xF0\x9F\x92\xA3"

main() {
  echo
  echo "============================================"
  prompt "starting run ..."

  if compile; then
    echo > /dev/null
  else
    fail
  fi

  if do_run $@; then
    succeed
  else
    fail
  fi

  echo "============================================"
  echo
}

do_run() {
  chapter=$1
  section=$2
  exercise=$3
  shift
  shift
  shift
  java_args=$@
  java_package=algsex.chapter$chapter.section$section.Exercise$exercise
  command="java -enableassertions -cp $JAVA_DEPS_DIR/*:$JAVA_OUTPUT_DIR $java_package $java_args"

  prompt "running command $BLUE$command$NO_COLOR"
  echo "==="
  $command
  echo "==="
}

succeed() {
  prompt "${GREEN}${CHECK_ICON} run succeeded$NO_COLOR"
  exit 0
}

fail() {
  prompt "${RED}${ERROR_ICON} run failed$NO_COLOR"
  exit 1
}

main $@