#!/usr/bin/env bash
RED="\u001b[31m"
GREEN="\u001b[32m"
BLUE="\u001b[34m"
NO_COLOR="\u001b[0m"
CHECK_ICON="\xE2\x9C\x85"
ERROR_ICON="\xF0\x9F\x92\xA3"

main() {
  prompt -b
  prompt -b "============================================"
  prompt "starting run ..."

  compile || fail

  if do_run $@; then
    succeed
  else
    fail
  fi

  prompt -b "============================================"
  prompt -b
}

do_run() {
  java_package=$1
  shift
  java_args=$@
  compile_java_command="java -enableassertions --class-path $JAVA_DEPS_DIR/*:$JAVA_OUTPUT_DIR $java_package $java_args"

  export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0

  if [ $QUIET ]; then
    unset TIME
    command="$compile_java_command"
  else
    export TIME="===\n%E elapsed"
    command="time $compile_java_command"
  fi

  prompt "running command $BLUE$command$NO_COLOR"
  prompt -b "==="
  $command
  command_result=$?
  prompt -b "==="

  return $command_result;
}

succeed() {
  prompt "${GREEN}${CHECK_ICON} run succeeded$NO_COLOR"
  exit 0
}

fail() {
  prompt "${RED}${ERROR_ICON} run failed$NO_COLOR"
  exit 1
}

main $@