#!/usr/bin/env bash
main() {
  command="run-ex $@"

  chapter=$1
  section=$2
  exercise=$3
  exercise_file=./src/chapter_$chapter/section_$section/Exercise$exercise.java
  support_dir=./src/support

  $command

  while inotifywait -q -e close_write $exercise_file $support_dir; do
    $command
  done
}

main $@